sudo: required

services:
  - docker

language: cpp

compiler:
  - clang
  - gcc

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always

before_install:
  - docker pull praqma/native-gradle:latest

script:
  - cat /etc/*-release
  - clang --version
  - gcc --version
  - java -version
  - ls -al ${PWD}
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-gradle:latest ./build.sh
  - docker run --rm --workdir=/workspace --volume ${PWD}:/workspace praqma/native-gradle:latest ./test.sh